### ISSUE TITLE
Allow for RegEx matching in assertions

### ISSUE THREAD

**Issue by tnolet** [checkly/product-roadmap#15]
We want to be able to use regular expressions with capture brackets to grab arbitrary data from headers and possibly other HTTP response properties.

An example provided by a user is capturing the `max-age` value of an HSTS header:

```
 /max-age=\d+?; includeSubDomains; preload/
```

**Comment by tnolet** [comment]
Regexes are progressing nicely.  Regexes can be added to Headers and Text body sources.
For JSON we have JSON path.

![image](https://user-images.githubusercontent.com/3802923/58494282-0bc30e00-8175-11e9-964a-80da9a981a16.png)

**Comment by mwl** [comment]
@tnolet As I understand it, it's the first (or only) group that's parsed on to the comparison step?

**Comment by tnolet** [comment]
@mwl correct. This will be made clear in the docs. Only the first capturing group is passed into the rest of the assertion pipeline.

Here is a preview snippet of the docs:

## Using regular expressions

Regular expressions give you the power to extract specific parts of text from a larger text using **capturing groups**. You can use regular expressions with two assertions sources:

1. **Text body:** Use the property field to add your regex.
2. **Headers:** First select the header your interested in in the property field, then click "add regex".

Under the hood, we use the stock Javascript regular expressions implementation. Specifically, we use the [.match()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match) method. We *do not use the `/g` modifier* and return the first matched group the expression finds.

Sounds more complicated than it is. Here is an example:

```javascript

const paragraph = 'The quick brown fox jumps over the lazy dog. It barked.'
const regex = /quick (.*) fox/
const found = paragraph.match(regex)
console.log(found)

// [ 'quick brown fox',
//  'brown',
//  index: 4,
//  input: 'The quick brown fox jumps over the lazy dog. It barked.' ]
```

In the example above we return the string `brown` because it is the first capture group, the `(.*)` bit. The first item `quick brown fox` is the full match, we do not return.
