### ISSUE TITLE
Export history alerts to CSV

### ISSUE THREAD

**Issue by pvatterott** [checkly/product-roadmap#153]
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

**Is your feature request related to a problem? Please describe.**
This has come up during our SOC 2 audit. We're using Checkly to satisfy our controls around system availability checks & alerting. As a part of evidence collection, our auditor has requested a history of alerts throughout the audit period.

**Describe the solution you'd like**
It would be great if I could, from the 'check' view, download a CSV of all alerts from a given time perio.

Just seeing the history of alerts in the application would also be helpful.

**Describe alternatives you've considered**
I took screenshots of the alert emails and support provided me with a CSV export.

**Additional context**
Although alerting is the highest priority, it would also be great to be able to export the history of all check results for a given check and to export the events that caused the alert

My long shot goal would be to automatically export the alerts periodically and upload to our compliance system (tugboat logic)

**Comment by tnolet** [comment]
@pvatterott I just reread your initial issue.
You mention

> Just seeing the history of alerts in the application would also be helpful.

This view is available in the app on the "events" tab for each check, but also at the global level under https://app.checklyhq.com/events

Events co-mingle alerts with deployment events though.

Having said this, we will stil introduce a `v1/check-alerts` public API endpoint to give you direct API access to all alert events.

**Comment by case** [comment]
This is a bit hacky, but if the website view has a clean-ish table with the data in it, you could grab it with something like Table Capture: https://www.georgemike.com/tablecapture/

**Comment by tnolet** [comment]
@case @pvatterott we have PR for this in review. More news soon.

**Comment by tnolet** [comment]
@case @pvatterott we just shipped an extra public API endpoint `/v1/check-alerts` that should enable you to create an export of alerts. As mentioned, we opted for a more generic approach here instead of a "download as CSV" button in the UI.

You can read the details either on our OpenAPI / Swagger doc [1] or in the API docs on the site [2]
1. https://api.checklyhq.com/#/Check%20alerts/getV1Checkalerts
2. https://www.checklyhq.com/docs/api#tag/Check-alerts

**Comment by pvatterott** [comment]
Thank you @tnolet and team!! Really appreciate you taking my feedback into consideration
