### ISSUE TITLE
Terraform provider

### ISSUE THREAD

**Issue by mwl** [checkly/product-roadmap#21]
**Is your feature request related to a problem? Please describe.**
When trying to maintain 8 (or more) exactly equal checks it's a bit of a pain to keep them aligned, i.e. adding tags, assertions, scheduling etc.

**Describe the solution you'd like**
We use [Terraform](https://www.terraform.io) for configuring most other 3rd party services, and it's very powerful for maintaining cloud services over time.

**Describe alternatives you've considered**
Ansible might be an alternative, but I don't find it particularly great for maintaining a specific state.

**Additional context**
Terraform already has providers for a few competing services.

**Comment by tnolet** [comment]
@mwl this is an excellent idea. We are first going to release a public API to actually provide the option for this type of extension. After that, this will be bumped on the roadmap.

**Comment by tnolet** [comment]
@mwl There is a really early version of a Terraform provider being build at https://github.com/bitfield/terraform-provider-checkly for another Checkly customer.

John (the maintainer) and I are in constant contact about the bugfixes to the API and the general progress. This provider uses the Checkly Go SDK https://github.com/bitfield/checkly which is also in active development.

**Comment by tnolet** [comment]
@mwl the Terraform provider is out and in usage! We're working on the docs but the examples should already point you in the right direction

https://github.com/bitfield/terraform-provider-checkly
