### ISSUE TITLE
Read Only - Allow users to view steps in test script

### ISSUE THREAD

**Issue by OlllllllO** [checkly/product-roadmap#24]
**Is your feature request related to a problem? Please describe.**
When I grant a user "Read Only" access they are unable to review the steps associated with the tests script. This would be helpful for others to view scripts without the ability to change them.

**Describe the solution you'd like**
Allow users with Read Only access to view all steps of the script for API/Browser tests.

**Describe alternatives you've considered**

1. If a developer needs to review script give them write access.
2. Use Terraform to manage the scripts via source control. Related: https://github.com/checkly/product-roadmap/issues/21

**Comment by tnolet** [comment]
@OlllllllO part 1 of this request is now live! Users with only read access can now view all the screens and tabs related to editing a check. They can still not edit though. I'm closing this issue as part 2 is already covered by #21

**Comment by OlllllllO** [comment]
@tnolet - looks great!
