### ISSUE TITLE
Pushover support

### ISSUE THREAD

**Issue by ryanchapman** [checkly/product-roadmap#26]
**Is your feature request related to a problem? Please describe.**
I'd like to use Pushover for alert notifications

**Describe the solution you'd like**
Add an integration for Pushover similar to your Pagerduty integration.  If that's too difficult, it would be nice if the webhook feature let me specify a custom payload.  In New Relic, I can do urgent alerting (`priority=2`) that causes my phone to keep dinging until I acknowledge it, which is effective at waking me up in the middle of the night:

```
token=my_secret_pushover_token
user=my_pushover_user_string
title=$EVENT_TYPE $INCIDENT_ID ($POLICY_NAME)
html=1
priority=2
retry=30
expire=10800
message=$EVENT_DETAILS<br>$INCIDENT_URL
```

**Describe alternatives you've considered**
I've tried webhook, but couldn't figure out how to specify a custom POST payload.

**Additional context**

**Comment by tnolet** [comment]
@ryanchapman thanks for contributing this feature request. I think your proposal for editable/customizable webhook template is a great one. This could solve many similar cases.

I will create parent issue for this.

**Comment by tnolet** [comment]
@ryanchapman You can now create custom webhooks! Have a look here:

https://checklyhq.com/docs/alerting/webhooks/

Just make sure to form encode the payload, as I think Pushover expects that.
