### ISSUE TITLE
Alertmanager integration

### ISSUE THREAD

**Issue by Bekt** [checkly/product-roadmap#27]
**Is your feature request related to a problem? Please describe.**
Alert channel integration with [Prometheus Alertmanager](https://github.com/prometheus/alertmanager).

**Describe the solution you'd like**
Similar to others such as Pagerduty. They key difference here is Alertmanager expects open incidents to constantly fire, rather than one-time. It considers an incident to be resolved when it stops sending firing alerts.

**Describe alternatives you've considered**
The current webhook integration could work if the payload was customizable. 

**Additional context**
API: http://petstore.swagger.io/?url=https://raw.githubusercontent.com/prometheus/alertmanager/master/api/v2/openapi.yaml#/alert/postAlerts

**Comment by tnolet** [comment]
@Bekt we just pushed live custom webhook payload. Have a look here:

https://checklyhq.com/docs/alerting/webhooks/

Can you let me know if this is sufficient for your use case?
