### ISSUE TITLE
Customizable templates for Webhook requests

### ISSUE THREAD

**Issue by tnolet** [checkly/product-roadmap#28]
**Is your feature request related to a problem? Please describe.**
Users want to trigger external services that require specific payload in the request body. Now, the webhook body is a fixed entity requiring either interception by the user and retriggering, or individual integrations for each service requested.

**Describe the solution you'd like**
Provide a template system where users can create templates and use variables that map to the various parts of a check alert, i.e. check name, response time etc.

A user should be able to create multiple templates and assign them to individual webhook alerts.

**Comment by tnolet** [comment]
https://github.com/checkly/product-roadmap/issues/27

**Comment by tnolet** [comment]
https://github.com/checkly/product-roadmap/issues/26

**Comment by tnolet** [comment]
This is now live

**Comment by ryanchapman** [comment]
Thanks for being so responsive to your users Tim!

This is working great with Pushover.  For anyone that wants to use that, here is an example that will alert until a human acknowledges it on their phone (`"priority":2`):

```
{"token":"FILL_IN_YOUR_SECRET_TOKEN_FROM_PUSHOVER",
"user":"FILL_IN_YOUR_USER_FROM_PUSHOVER",
"title":"{{ALERT_TITLE}}",
"html":1,
"priority":2,
"retry":30,
"expire":10800,
"message":"{{ALERT_TYPE}} <br>{{STARTED_AT}} ({{RESPONSE_TIME}}ms) <br>{{RESULT_LINK}}"}
```
