### ISSUE TITLE
Assertion: contains operation

### ISSUE THREAD

**Issue by Bekt** [checkly/product-roadmap#33]
**Is your feature request related to a problem? Please describe.**
Would be nice to do a basic `text body CONTAINS string` in response [assertions](https://checklyhq.com/docs/api-checks/assertions/).

**Describe alternatives you've considered**
#15 

**Additional context**
Regex would work but might be an overkill for simple cases. This would be most relevant for HTML pages.

**Comment by tnolet** [comment]
Hey @Bekt what a coincidence! This is part of the upcoming release. Currently in last stages of testing. 

![image](https://user-images.githubusercontent.com/3802923/59404065-74c99900-8da5-11e9-9087-7c1abec92213.png)

**Comment by Bekt** [comment]
woohoo!
