### ISSUE TITLE
Slack integration: specify channel name

### ISSUE THREAD

**Issue by Bekt** [checkly/product-roadmap#34]
Currently, Checkly let's specifying a global Slack webhook URL at the account/team level. However, it is not possible to use this webhook at a check level while specifying a different channel name.

**Describe alternatives you've considered**
Different webhook for every channel.

**Additional context**
It is possible to use one webhook URL and specify a channel name on a request. https://api.slack.com/custom-integrations/incoming-webhooks

**Comment by batuhan** [comment]
Hey @Bekt,

Happy to say we've just shipped this.

Check out the updated docs on our Slack alerting channel: https://checklyhq.com/docs/alerting/slack/

Let me know if you have any issues with it or have any feedback!
