### ISSUE TITLE
Support multiple Pagerduty Integrations

### ISSUE THREAD

**Issue by ryanchapman** [checkly/product-roadmap#38]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to alert different teams through Pagerduty.  For example, if I have a check for API, then I'd like for it to alert the API team in Pagerduty.  If I have a check for web, then I'd like for it to alert the web team in Pagerduty.  Seems that currently you can only alert one team in Pagerduty.

**Describe the solution you'd like**

A way to associate a check with a specific Pagerduty team.  Since we can only alert one Pagerduty team, right now we have to alert a triage team which then forwards the alert to the correct team.

**Describe alternatives you've considered**

**Additional context**

**Comment by tnolet** [comment]
@ryanchapman thanks for adding this!

**Comment by tnolet** [comment]
@ryanchapman @mwl this feature is landing in the next major update. You can create as many Pagerduty channels as you like and assign individual checks to them.

Please see https://github.com/checkly/product-roadmap/issues/45

We needed to refactor alerting before shipping the grouping feature, so I guess you're lucky ;o)

**Comment by mwl** [comment]
@tnolet Interesting. Looking very much forward to that. Let me know if I can be of any help.

**Comment by tnolet** [comment]
@ryanchapman @mwl this feature is now live. Hope it helps!
