### ISSUE TITLE
System context environment variables

### ISSUE THREAD

**Issue by mwl** [checkly/product-roadmap#40]
**Is your feature request related to a problem? Please describe.**
We would like to be able to inject the datacenter location into the body of the request

**Describe the solution you'd like**
Could be done via the environment variables notation, i.e. `{{CHECKLY_DATACENTER}}`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by tnolet** [comment]
This change is now live. Access the data center location using the `REGION` variable, i.e.

```js
const region = environment['REGION']
```

https://checklyhq.com/docs/api-checks/setup-teardown-scripts/#built-in-variables
