### ISSUE TITLE
Add support for code definitions of checks

### ISSUE THREAD

**Issue by mattmcf** [checkly/product-roadmap#41]
**Issue**
Checkly does not natively support an integration with source control. It is extremely important that developers can save, edit, collaborate on and deploy changes to their defined code snippets, http checks and browsers checks. Since Checkly is itself the only source of truth for the check, it's really easy to accidentally obliterate the snippet you spent hours tuning.

You can use Checkly's HTTP API to get definitions for each of the check and snippet objects, but they're difficult to parse and reason about in any source control repository. (ie. the body of a snippet is saved as a single long string.) Support for a source controlled definitions would allow developers to build complicated checks with confidence that their work will persist.

**Prospective Solution**
It'd be excellent to expose a Checkly to technology like Terraform where I can specify my exact configuration in a code format. That way I can save it in source control and always revert back to a known state. The parameters that define a check / snippet would be parameters, but it'd also be great to have fine grained controls on the context of a browser check / snippet. I'm imagining how Gitlab allows you to specify a list of commands to run within a job. That format would work nicely for browser checks / snippets.

On my own, I could define a build pipeline that would automatically apply the infrastructure changes whenever the underlying definitions change.

**Comment by tnolet** [comment]
@MattRMcFarland thanks for adding this Matt. To wet your appetite, the Terraform provider is just out integration testing and we'll package and distribute it very soon.

https://github.com/bitfield/terraform-provider-checkly

More news on this soon!

**Comment by tnolet** [comment]
@MattRMcFarland short update on this:
- Terraform provider is now live, tested and used by Checkly customers. Check https://github.com/bitfield/terraform-provider-checkly 
We're working on some more extensive documentation.

- A Github integration is coming next week. This integration does not tackle storing checks as files in source code yet, but the first steps are there.

**Comment by tnolet** [comment]
@mattmcf I'm closing this one:

- we have a fully fledged TF provider right now https://www.checklyhq.com/docs/terraform-provider/
- we are using a new tracking ways of defining checks in your codebase here: https://github.com/checkly/public-roadmap/issues/213

**Comment by mattmcf** [comment]
@tnolet sounds great!
