### ISSUE TITLE
Add an option to increase check timeout

### ISSUE THREAD

**Issue by lucleray** [checkly/product-roadmap#42]
**Is your feature request related to a problem? Please describe.**
For some of my use case, I'd like to be able to increase the current 8 second timeout to something longer.

**Describe the solution you'd like**
Add an option to set the timeout in the check configuration options. I'd like to increase to up to one minute.

**Describe alternatives you've considered**
There's no real alternative at the moment.

**Comment by tnolet** [comment]
@lucleray we just updated the hard timeout to 30 seconds. This is still an experiment and we'll run it for at least a week. After that week I'll see how it measures up and if we need to tweak this more.

**Comment by lucleray** [comment]
@tnolet Amazing, thanks!

**Comment by tnolet** [comment]
@lucleray we're sticking to the 30 second runtime for API checks for now. Closing this ticket.
