### ISSUE TITLE
Add option to set a soft limit timeout on checks

### ISSUE THREAD

**Issue by lucleray** [checkly/product-roadmap#43]
**Is your feature request related to a problem? Please describe.**
For some of my checks, I'd like to be able to have alerts when the call is taking too long.

**Describe the solution you'd like**
A "soft limit" timeout option that triggers an alert when it's reached would help me solve that problem.

**Describe alternatives you've considered**
Look at the graph to see any spike. But that doesn't trigger alerts.

**Comment by tnolet** [comment]
This is now live! Please see https://checklyhq.com/docs/api-checks/limits/
