### ISSUE TITLE
Allow choosing an HTTP method for WebHooks

### ISSUE THREAD

**Issue by baaken** [checkly/product-roadmap#49]
**Is your feature request related to a problem? Please describe.**
We are using statuspage.io. The WebHook functionality is super flexible and allows us to create incidents with their API. Unfortunately, updating incidents or components (degraded service etc.) is not possible because this requires PUT or PATCH functionality.

**Describe the solution you'd like**
I would like to be able to select between the following methods for WebHooks:
* POST
* PUT

**Describe alternatives you've considered**
Alternatively, a complete statuspage.io integration would be fantastic of course, at least for incidents and component degradation. I am available for discussing the specs if relevant enough.

**Additional context**
This is the method I'd like to use: https://developer.statuspage.io/#operation/putPagesPageIdComponentsComponentId

**Comment by umutuzgur** [comment]
Hi @baaken!

Happy to let you know we just enhanced our webhook configuration. It supports different http methods, headers and query params now. Thanks for the creating the feature request!
