### ISSUE TITLE
Would prefer to stay logged into dashboard

### ISSUE THREAD

**Issue by slothstronaut** [checkly/product-roadmap#51]
**Is your feature request related to a problem? Please describe.**
I would prefer to stay logged for much longer, its a mild annoyance to have to login almost daily

**Describe the solution you'd like**
I would like to just stay logged in indefinitely, or at least for a more reasonable amount of time like 30 days

**Describe alternatives you've considered**
None

**Additional context**
I'm using social login with Google if it makes a difference.

**Comment by tnolet** [comment]
Hi @slothstronaut, there might be something going wrong here. The JWT tokens used are valid for 30 days already. As you can image, I used checkly quite a bit and I rarely have to log in again. I use Google login to for a internal Checkly account.

The access tokens are stored in the browser Local Storage. Are you erasing that maybe on a regular basis?

**Comment by slothstronaut** [comment]
That is strange. I'm definitely not erasing the tokens or clearing my localStorage, and am just going about logging in normally.

**Comment by slothstronaut** [comment]
Hey @tnolet here are some screenshots of my browser state when I am logged out: https://www.dropbox.com/s/d5ao4yw9ulqqm7e/Archive-checkly-screenshots.zip?dl=0

It contains the contents of `localStorage` and a few screenshots of the 401'd requests, hopefully this can help, but its a consistent issue across different browsers, machines and accounts.

I'm planning to signup for your plan on my own project and potentially at my work as well, but want to stay logged in ✌️

**Comment by tnolet** [comment]
@slothstronaut thanks for adding some context. I'm pretty sure the behaviour is regardless of social or email login. We are using Auth0 and the access_token we get from them is regardless of the credentials provider.

**Comment by tnolet** [comment]
One more note: we have not implemented this yet:

https://auth0.com/docs/libraries/auth0js/v9#using-checksession-to-acquire-new-tokens

Pretty sure this will make a "remember me" toggle possible

**Comment by slothstronaut** [comment]
Sure no problem. As for why you may remain logged in while I'm getting logged out could simply be due to how often the token is getting refreshed. I typically will check the stats once a day at the most, often a day or two between loading the site, so that could be a factor. Anywho, good luck!

**Comment by batuhan** [comment]
Hey there @slothstronaut!

Happy to say we've just rolled out an update to our integration with Auth0 including implementing refresh tokens. This should allow for longer sessions (up to 30 days). 

Please let me know if your experience is improved or if you have any more feedback.
