### ISSUE TITLE
Feature request: include handlebars-helpers

### ISSUE THREAD

**Issue by wvanderdeijl** [checkly/product-roadmap#55]
**Describe the solution you'd like**
Would it be possible to include the [handlebars-helpers](https://www.npmjs.com/package/handlebars-helpers) library to the server side checkly code when parsing handlebar templates?

**Additional context**
I am setting up Google Hangouts notifications as an alert mechanism from checkly. I would love to use a different icon URL in the notification payload based on the ALERT_TYPE being a failure or recovery. This could be a simple `eq` statement using a handelbars helper: https://www.npmjs.com/package/handlebars-helpers#eq
Adding a generic npm module with common helpers is probably more desirable than having checkly users supplying their own handlebars helpers when setting up alerts.

PS. Having these handlebar helpers might also come in handy when setting up the body for an API check in checkly.

**Comment by tnolet** [comment]
@wvanderdeijl this is a great addition. I was not aware of this set of helpers and I see no reason not to include it. Expect an update on this soon.

**Comment by batuhan** [comment]
Hey there @wvanderdeijl, 

We started working on this feature last week. We utilize Handlebars in a few places from Webhooks to API request fields. Basically, everywhere you can use snippets and/or environment variables is powered by Handlebars.

Especially after taking a good look at the library, your suggestion of implementing `handlebars-helpers` initially made sense to us & we wanted to make sure everywhere you can use templating, you can have access to the same set of features.

After starting the design phase of our implementation we noticed that for most of these helpers to provide benefits, we would need to provide some more variables and probably standardise the data we provide to the fields. This is achievable, of course, but isn't that straightforward. We don't want to build a half baked solution that's going to cause problems with backward compatibility in the future. If we build something & it works for you, it should keep working without any intervention for a long time.

So, *at least for now*, we've decided to change our decision and mark this request as `wontfix`. This is no way a final decision, we might come back to this if we are certain we can build it in a way that's going to provide good value to Checkly customers & not cause problems down the road.

I'm sure you're aware of this, you can use [the built-in helpers](https://handlebarsjs.com/guide/builtin-helpers.html) already with our Webhooks feature. I don't think we explicitly state it anywhere. So, your initial need to set a different URL per `ALERT_TYPE` is already possible but just a bit more verbose than it would've been with `handlebars-helpers` integrated.

Please let me know if you have a case where built-in helpers & other Checkly features are not enough to cover, we'll love to help & find solutions.

**Comment by wvanderdeijl** [comment]
It's a shame that implementing this is more complicated than expected. I understand you're hesitance to introduce a half-baked solution.

I've looked at the built-in helpers in trying to achieve my goal, but those are *very* limited. With an `#if` helper you can only check for "falsiness" of an attribute. I don't think you can use expressions there to achieve the goal of building a different webhook payload based on the `ALERT_TYPE`

Another option would be to let us define our own custom helpers in javascript which you could register as a helper when evaluating the template. But I guess that would add a lot of complexity to your code as well as the UI for us.

Oh well, I could always build my own little simple cloud function and invoke that from the checkly webhook. Then let the cloud function do its transformation and invoke the final webhook (google hangouts in my example)

**Comment by batuhan** [comment]
Hey @wvanderdeijl!

We've went back and made some changes to our Handlebars implementation that was included in our release today. We opted to add only a few of the helpers offered by the `handlebars-helpers` package but we have all the conditionals so your use case should be covered!

You can read more about this on our blog https://blog.checklyhq.com/changelog-template-variables-group-api/

**Comment by batuhan** [comment]
Also, please feel free to give us more feedback on how we can improve alerts and Checkly in general. You can always use this repository's issues for feature requests or our Intercom bubble to reach us for any questions or suggestions.
