### ISSUE TITLE
Improve Setup/Teardown script development

### ISSUE THREAD

**Issue by dijitali** [checkly/product-roadmap#62]
💡 For general support requests and bug reports, please go to [checklyhq.com/support](https://checklyhq.com/support)

**Is your feature request related to a problem? Please describe.**
I find it a bit difficult to test setup scripts when I'm developing them, especially when I need to reproduce the Checkly environment locally.  I can see error responses in the Dev Tools like this:
![image](https://user-images.githubusercontent.com/4665045/79891981-afef1c80-83f9-11ea-99b0-a150fc6ba57c.png)

And I can then try to work out the problem from the `/api-check-runs` response. 

**Describe the solution you'd like**
It would be useful if the "Run Request" button would show me any error output from any setup/teardown scripts.

**Describe alternatives you've considered**
It would also be great to have a blog post with a recommendation on how I might best reproduce the Checkly script environment locally when troubleshooting.  It's mentioned in the docs that scripts are wrapped in an async function; it would be handy to have a simple way of doing this locally and also perhaps pulling env vars from a file .

**Additional context**
N/A.  But I do love the setup/teardown script feature itself! 💯 👍 🌮

**Comment by tnolet** [comment]
@dijitali we actually accidentally broke the bubbling up of errors from scripts in the UI. This was fixed last week. Any uncaught scripting errors should now just show in the UI. Thanks for reporting!
